### PR TITLE
Renamed Java EE to Jakarta EE in ResourceNamingInjection

### PR DESCRIPTION
**Pull request by ganapathi004**
Signed-off-by: Ganapathi Basamsetti <ganapathibasamsetti@gmail.com>

### CODE REVIEW

**Comment by ggam** [comment]
JMS, EJB and other acronyms should be replaced with their new Jakarta name.

**Comment by ganapathi004** [comment]
Sure @ggam. For confirmation, I will replace the acronyms with their full Jakarta forms.So `...components of references to JMS...` becomes `...components of references to Jakarta Message Service...`. Also, Can I follow these new names for renaming [Renaming Java EE Specifications for Jakarta EE](https://blogs.eclipse.org/post/wayne-beaton/renaming-java-ee-specifications-jakarta-ee)

**Comment by ggam** [comment]
Yes. You can get the list of final names from https://docs.google.com/spreadsheets/d/18SraPxRBCOyaS6w-UV6TR-UA1bWy1--sV0ky6msAjWY/edit#gid=0 (I've found this document on https://github.com/eclipse-ee4j/jakartaee-tck/issues/67). JMS for example was renamed to "Jakarta Messaging".

**Comment by ganapathi004** [comment]
@ggam There are specification links to the [JCP](https://jcp.org). What are the equivalent of them for Jakarta?

**Comment by ganapathi004** [comment]
Hi @keilw, there are some more changes - Acronyms, spec names,etc Should I create another pull request?

**Comment by kwsutter** [comment]
Yes, @ganapathi004, please open a new PR.  @keilw should not have merged this PR until you were ready and we had at least one review approval.  Sorry for the confusion!  Thanks for your help with the doc updates!

**Comment by kwsutter** [comment]
Section 5 of the Platform spec is really messed up with this errant merge...  Not sure if it will be easier to revert this merge and start over or not...  Something to consider tomorrow...

**Comment by ganapathi004** [comment]
Hi Kevin,

I couldn't get which section you are referring to. Can you please clarify?

Regards,
Ganapati B

**Comment by kwsutter** [comment]
All of these changes were accidentally merged.  You'll just have to start fresh.  Thanks!

**Pull request merged**
