### PR TITLE
Removed Maven Enforcer JDK8

### PR DESCRIPTION
**Pull request by ggam**
I've successfully compiled the project with JDK 12.

### CODE REVIEW

**Comment by pzygielo** [comment]
@ggam - but enforcer enforces from two sides, and I think your success with JDK12 allows for following change:
```
<requireJavaVersion>
    <version>[1.8.0,)</version>
```
The lower limit can't be reduced, as with JDK7 `specification` will definitely not build due to dependencies used (e.g. `asciidoctor`).
Thus I'd propose to keep plugin configured, enforcing `1.8+`, as above.
And I'd like
```
<message>You need JDK8 or lower</message>
```
to be corrected, as currently it does not reflect rule (which fixes JDK to 1.8x), but also suggest that using earlier JDK is fine (which isn't).

**Comment by ggam** [comment]
@ivargrimstad Jakarta EE 8 targets Java SE 8 for runtime, but some specs already allow compilation with newer Java versions, and in fact most application servers support Java 11 nowadays. I think it's a good thing to allow compiling with latest Java whenever possible.

@pzygielo you're right, thanks. I've already changed it.

**Comment by pzygielo** [comment]
And how about that message displayed on rule violation?
```xml
<message>You need JDK8 or lower</message>
```

**Comment by ggam** [comment]
Embarrasing... Done!

**Comment by ggam** [comment]
The reason is that some people (like me) will have a newer JDK as a
default. With this, there's no need to change versions.

**Pull request merged**
