### PR TITLE
Update Jakarta EE Architecture image

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

First attempt at updating an image with inkscape. For the most part, it was quite easy.  But, I have now run into some areas that just are not working for me... Maybe someone can help me complete this PR?

I think the Client Container and Applet Container portions are fine.

But, on the EJB and Servlet Container images, I'm having problems with shading the optional boxes.  The boxes at the left end of the feature lists need to be shaded per the key in the diagram (gray color).  These include the jaxb, ws metadata, web services, jax-ws, and saaj boxes.

Thanks for the help!

### CODE REVIEW

**Comment by kwsutter** [comment]
I'll take assistance from anyone.  I'm just not that artistic to figure this out.  :-)  @cpusam?  @tjwatson?  Thanks!

**Comment by kwsutter** [comment]
Renaming both of these images to JakartaEE.. instead of JavaEE...

**Comment by cpusam** [comment]
@kwsutter I created the rectangle shape using only one rect, with the option Edit->Tiled Clone. To you edit only one of these rects, you need firstly select it and unlikit it from the parent rect, and so you will can edit te color of rect. 
1-select the rect
2-Click Edit -> Clone ->Unlink Clone
3-now to something the the rect and it will free for this.

**Comment by hussainnm** [comment]
Check my edit https://github.com/hussainnm/jakartaee-platform/commit/be04cd3ed31f21dc84b494d07ee9094bc068df2d

image

**Comment by kwsutter** [comment]
Finally getting back to this exercise!  Your edited image looks great, @hussainnm!  Thank you!  I didn't know how to incorporate your commit into this PR, so I ended up just copying your image and overlaying mine.  The end result looks good, but you didn't get all of the credit.  Hopefully, this comment block will provide you with appropriate recognition.  Thank you again!

**Comment by kwsutter** [comment]
Since this PR was Approved after @hussainnm provided the updated image, then I'm going to go ahead with this merge.  If there are more tweaks required, they can be done via a separate PR.

**Pull request merged**
