### PR TITLE
Hilite that CORBA and Orb References are Optional

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

I just re-reviewed the requirements as outlined in Issue #300, and this is the only section that I think needs any modification.  I moved this "CORBA is optional" message from the end of this subsection to the top and highlighted it.  I think the rest of the Platform spec is good with the CORBA as an optional technology message.

### CODE REVIEW

**Comment by kwsutter** [comment]
Once approved, this PR would resolve Issue #300.

**Review by scottmarlow — APPROVED** [review]

**Comment by dblevins** [comment]
I think we should more directly mark this as optional rather than transitively imply it by linking it to interoperability.  The two are actually independent.

 * In EJB 1.1 
   * `java:comp/env/ORB` was a requirement
   * Servers may or may not use CORBA under the covers for their own purposes
   * There were no interoperability requirements or interop tests
 * In EJB 2.0
   * `java:comp/env/ORB` is still a requirement
   * Servers must support CORBA in addition to any other protocols they chose
   * There are interoperability requirements and interop tests

The above is simply to illustrate the not all CORBA-related requirements are tied to interoperability.  There are three distinct types of CORBA requirements:

 a. Exposing CORBA as a service that applications can use to call legacy systems.  The `java:comp/ORB` requirement falls into this category.   The server may or may not support CORBA itself.  The application may not even have remote EJBs of any kind.  The app is simply a client to a legacy system.  These requirements were introduced in EJB 1.1.
 b. Enabling servers to use CORBA as their protocol.  The "RMI-IIOP" serialization requirements for parameters and arguments of an EJB Remote Object or Home.  The server may or may not support CORBA itself for its own internal communication, however, the application must behave as if the server does and not break any serialization rules that would prevent CORBA from being used under the covers.  These requirements were introduced in EJB 1.1.
 c. Defining full remote interoperability between heterogeneous (cross-vendor) servers via CORBA complete with distributed security (CSIv2) and distributed transactions.

Our current status is C has been fully removed, B is still a requirement and A is now becoming optional.  A being optional is not tied to C as is incorrectly implied in the PR.  The status of A or C has no affect on B, which also means we cannot replace it with something vague like "COBRA is optional."

The most accurate and minimal thing we can do is:
 - Add "(optional)" in the title of the "ORB References" section like we did in a few sections of the EJB spec.
 - Update your "NOTE" to say something like, "Support for CORBA as an application service for contacting legacy systems is optional" or more tersely but perhaps lacking color/clarity "Support for CORBA as an application service is optional."

We could add the description of A, B and C to the spec so this is clear and the definitions considered cannon.  Maybe a nice clean table with three rows and a second column that contains the status word "optional", "required" or "removed.  I'm fine if we don't, however, I am sensitive that this is a repeat topic and without a clear statement we fall back into ambiguity/confusion.

My suggestion would be we update this PR with the title and "NOTE" change and if people like the sound of a table, I can work that up in a different PR.

**Review by dblevins — CHANGES_REQUESTED** [review]
I think we should more directly mark this as optional rather than transitively imply it by linking it to interoperability.  The two are actually independent.

 * In EJB 1.1 
   * `java:comp/env/ORB` was a requirement
   * Servers may or may not use CORBA under the covers for their own purposes
   * There were no interoperability requirements or interop tests
 * In EJB 2.0
   * `java:comp/env/ORB` is still a requirement
   * Servers must support CORBA in addition to any other protocols they chose
   * There are interoperability requirements and interop tests

The above is simply to illustrate the not all CORBA-related requirements are tied to interoperability.  There are three distinct types of CORBA requirements:

 - **a**. Exposing CORBA as a service that applications can use to call legacy systems.  The `java:comp/ORB` requirement falls into this category.   The server may or may not support CORBA itself.  The application may not even have remote EJBs of any kind.  The app is simply a client to a legacy system.  These requirements were introduced in J2EE 1.2 (EJB 1.1) and being made optional in Jakarta EE 9.1.
 -  **b**. Enabling servers to use CORBA as their protocol.  The "RMI-IIOP" serialization requirements for parameters and arguments of an EJB Remote Object or Home fall into this category.  The server may or may not support CORBA itself for its own internal communication, however, the application must behave as if the server does and not break any serialization rules that would prevent CORBA from being used under the covers.  These requirements were introduced in EJB 1.1 and are still required.
 -  **c**. Defining full remote interoperability between heterogeneous (cross-vendor) servers.  The requirements for distributed security via CSIv2 and distributed transactions that were defined in the removed EJB 3.2 chapter 10 fell into this category.  These requirements were introduced in EJB 2.0 and removed in Jakarta Enterprise Beans 4.0 and Jakarta EE 9.0.

Our current status is **C** has been fully removed, **B** is still a requirement and **A** is now becoming optional.  **A** being optional is not tied to **C** as is incorrectly implied in the PR.  The status of **A** or **C** has no effect on **B**, which also means we cannot replace it with something vague like _"COBRA is optional."_

The most accurate and minimal thing we can do is:
 - Add "(optional)" in the title of the "ORB References" section like we did in a few sections of the EJB spec.
 - Update your "NOTE" to say something like, _"Support for CORBA as an application service for contacting legacy systems is optional"_ or more tersely but perhaps lacking color/clarity _"Support for CORBA as an application service is optional."_

We could add the description of A, B and C to the spec so this is clear and the definitions considered cannon.  Maybe a nice clean table with three rows and a second column that contains the status word "optional", "required" or "removed.  I'm fine if we don't, however, I am sensitive that this is a repeat topic and without a clear statement we fall back into ambiguity/confusion.

My suggestion would be we update this PR with the title and "NOTE" change and if people like the sound of a table, I can work that up in a different PR.

**Comment by kwsutter** [comment]
> I think we should more directly mark this as optional rather than transitively imply it by linking it to interoperability. The two are actually independent.

Fair enough.  But, note that I was merely just moving a statement that was previously in the Spec section to a more noticeable area of the section.  We can attempt to clarify this further...

> The most accurate and minimal thing we can do is:
> - Add "(optional)" in the title of the "ORB References" section like we did in a few sections of the EJB spec.
> - Update your "NOTE" to say something like, "Support for CORBA as an application service for contacting legacy systems is optional" or more tersely but perhaps lacking color/clarity "Support for CORBA as an application service is optional."

I can do this.  I'll update the PR shortly.  Adding "optional" is easy and does make it stand out more.  And, I like your first suggestion for rewording the Note.  Thanks!

>  My suggestion would be we update this PR with the title and "NOTE" change and if people like the sound of a table, I can work that up in a different PR.

Will do with updating the PR and Note change.

Personally, I think we're kicking a dead horse by continuing to expand on the history of these CORBA requirements.  I understand that sometimes we need to understand the history so that we don't repeat the errors of our ways.  But, with every release, we get closer and closer to just removing all of this CORBA and Orb stuff from the Platform.  So, instead of adding more historical perspective to the Specification, we should focus on just removing it with the next major release (Jakarta EE 10).  My two cents worth...  Thanks.

**Review by ivargrimstad — APPROVED** [review]

**Review by dblevins — APPROVED** [review]
Looks good!

**Comment by dblevins** [comment]
> I think we should more directly mark this as optional rather than transitively imply it by linking it to interoperability. The two are actually independent.
> 
> * In EJB 1.1
>   
>   * `java:comp/env/ORB` was a requirement
>   * Servers may or may not use CORBA under the covers for their own purposes
>   * There were no interoperability requirements or interop tests
> * In EJB 2.0
>   
>   * `java:comp/env/ORB` is still a requirement
>   * Servers must support CORBA in addition to any other protocols they chose
>   * There are interoperability requirements and interop tests
> 
> The above is simply to illustrate the not all CORBA-related requirements are tied to interoperability. There are three distinct types of CORBA requirements:
> 
> * **a**. Exposing CORBA as a service that applications can use to call legacy systems.  The `java:comp/ORB` requirement falls into this category.   The server may or may not support CORBA itself.  The application may not even have remote EJBs of any kind.  The app is simply a client to a legacy system.  These requirements were introduced in J2EE 1.2 (EJB 1.1) and being made optional in Jakarta EE 9.1.
> * **b**. Enabling servers to use CORBA as their protocol.  The "RMI-IIOP" serialization requirements for parameters and arguments of an EJB Remote Object or Home fall into this category.  The server may or may not support CORBA itself for its own internal communication, however, the application must behave as if the server does and not break any serialization rules that would prevent CORBA from being used under the covers.  These requirements were introduced in EJB 1.1 and are still required.
> * **c**. Defining full remote interoperability between heterogeneous (cross-vendor) servers.  The requirements for distributed security via CSIv2 and distributed transactions that were defined in the removed EJB 3.2 chapter 10 fell into this category.  These requirements were introduced in EJB 2.0 and removed in Jakarta Enterprise Beans 4.0 and Jakarta EE 9.0.
> 
> Our current status is **C** has been fully removed, **B** is still a requirement and **A** is now becoming optional. **A** being optional is not tied to **C** as is incorrectly implied in the PR. The status of **A** or **C** has no effect on **B**, which also means we cannot replace it with something vague like _"COBRA is optional."_
> 
> The most accurate and minimal thing we can do is:
> 
> * Add "(optional)" in the title of the "ORB References" section like we did in a few sections of the EJB spec.
> * Update your "NOTE" to say something like, _"Support for CORBA as an application service for contacting legacy systems is optional"_ or more tersely but perhaps lacking color/clarity _"Support for CORBA as an application service is optional."_
> 
> We could add the description of A, B and C to the spec so this is clear and the definitions considered cannon. Maybe a nice clean table with three rows and a second column that contains the status word "optional", "required" or "removed. I'm fine if we don't, however, I am sensitive that this is a repeat topic and without a clear statement we fall back into ambiguity/confusion.
> 
> My suggestion would be we update this PR with the title and "NOTE" change and if people like the sound of a table, I can work that up in a different PR.

**Comment by dblevins** [comment]
Didn't mean to close.  Was trying to reply, saw I selected the wrong comment and accidentally closed the issue when trying to clean up.

**Comment by dblevins** [comment]
> Personally, I think we're kicking a dead horse by continuing to expand on the history of these CORBA requirements. I understand that sometimes we need to understand the history so that we don't repeat the errors of our ways. But, with every release, we get closer and closer to just removing all of this CORBA and Orb stuff from the Platform. So, instead of adding more historical perspective to the Specification, we should focus on just removing it with the next major release (Jakarta EE 10). My two cents worth... Thanks.

I'm fine with that.  As mentioned my only hesitation is that every time someone paints CORBA with a broad or inaccurate brush, I have to go kick the dead horse again.  I'd rather have a link to a document that explains it.  I'd be happy for us to post it anywhere.  Maybe I could put something in our website docs?

For expectation management, we will not be able to remove the class B set of requirements in Jakarta EE 10.  As long as we have vendors using CORBA as their protocol we'll need the class B requirements as they basically detail the restrictions app developers must follow so they don't interfere with the server's ability to use COBRA.  Use of `PortableRemoteObject.narrow` is in class B, for example.

**Comment by kwsutter** [comment]
> I'm fine with that. As mentioned my only hesitation is that every time someone paints CORBA with a broad or inaccurate brush, I have to go kick the dead horse again. I'd rather have a link to a document that explains it. I'd be happy for us to post it anywhere. Maybe I could put something in our website docs?

I know I am one of those that paints with a broad brush...  :-)  But, let's not lose this thought process (again).  I'll create a separate Issue and we can decide where to document this -- in the Specifications, on our Wiki, on our github pages, somewhere so that we have a place to reference.  Thanks!

**Comment by kwsutter** [comment]
One last question for you, @dblevins.  Are you satisfied that this is the only change required to complete Issue #300?  From my reading of the Spec where we talk about CORBA, I think this was the only questionable area left in the Platform Spec.  But, if can review that Issue and my comments on that Issue, I'd appreciate another set of eyes to keep me honest.  Thanks!

**Comment by dblevins** [comment]
> > I'm fine with that. As mentioned my only hesitation is that every time someone paints CORBA with a broad or inaccurate brush, I have to go kick the dead horse again. I'd rather have a link to a document that explains it. I'd be happy for us to post it anywhere. Maybe I could put something in our website docs?
> 
> I know I am one of those that paints with a broad brush... :-) 

It's perfectly ok and expected.  I'd be far more alarmed if we had a community of CORBA experts as then we'd be unlikely to get rid of it :)  (to the extent we can get rid of it)

> But, let's not lose this thought process (again). I'll create a separate Issue and we can decide where to document this -- in the Specifications, on our Wiki, on our github pages, somewhere so that we have a place to reference. Thanks!

Sounds great.

**Pull request merged**
