### PR TITLE
Various errata corriges.

### PR DESCRIPTION
**Pull request by DmitriGit**
Hello,

here are the following corrections:

1) Tooltip "XML" in some blocks of XML code is absent. For example in the section "6.2.2.6. Declaring Permissions Required by Application Components" - in the block after "The following is an example of a permission set declaration:",

2) Prefix and postfix ". . ." in some XML blocks are absent, such as:
     a. in the section "5.22. Managed Bean References" in the block after "The following example shows how to declare references to the shopping cart bean..."
     b. in the section "5.18.8. Connector Administered Object Definition" in the block after "An administered object resource may be defined in a web module, enterprise bean..."

and others...

3) in the paragraph "6.4. Servlet 5.0 Requirements" after the phrase:
"Web containers must support Jakarta EE distributable web applications placing objects of any of the following types (when supported by the Jakarta EE product) into a jakarta.servlet.http.HttpSession object using the setAttribute or putValue methods:"
"java.io.Serializable" must be part of the list I think.

4) in the "6.2.2.1. Jakarta EE Product Provider’s Responsibilities", there is an extra line between the "Note that, on some installations of Jakarta EE products, the security policy of the installation may be such that applications are granted fewer permissions than those defined in" and "Jakarta EE Security Permissions Set and, as a result, some applications..."

5) In "6.30" I see: "The DI specification can be found at:"
    but in all others ("6.31, 6.32, 6.33, 6.34 and 6.35") I see only "The Enterprise Web Services specification can be found at..." even if all that are about of:
     a) "Enterprise Web Services 2.0",
     b) "XML Binding 3.0 Requirements",
     c) "XML Web Services 3.0 Requirements",
     d) "Web Services Metadata 3.0 Requirements" and
     e) "SOAP with Attachments 2.0 Requirements"
arguments.

Thank you!
Dmitri.

### CODE REVIEW

**Comment by DmitriGit** [comment]
I continue to read the "Platform Specification" - let me 1 week please for this PullRequest - don't close it, ok? 

If I'll find some other observations I'll add them here, if not - I'll let you know and we can close the PR.

Thank you!
Dmitri.

**Comment by ivargrimstad** [comment]
I'll convert it to Draft. You can change it to "Ready for Review" when you're done. OK?

**Comment by DmitriGit** [comment]
> I'll convert it to Draft. You can change it to "Ready for Review" when you're done. OK?

Ah, ok!!! Yes - it's better! Sorry, but I didn't know about it.

Thank you very much Ivar!

**Comment by DmitriGit** [comment]
Hello,

I can be wrong but at the start of "8.4.1. Assembling a Jakarta EE Application", the phrase "_1. Reconcile Jakarta EE module deployment descriptors._" should be: "**3.** _Reconcile Jakarta EE module deployment descriptors_." (that is with "**3.**" prefix and not "1.").

If you confirm me I'll correct that also.

Thank you,
Dmitri.

**Comment by kwsutter** [comment]
> I can be wrong but at the start of "8.4.1. Assembling a Jakarta EE Application", the phrase "_1. Reconcile Jakarta EE module deployment descriptors._" should be: "**3.** _Reconcile Jakarta EE module deployment descriptors_." (that is with "**3.**" prefix and not "1.").

Well, @DmitriGit, it's even worse than the requested update to "3"...  If you take a look at the original [Java EE 8 Platform Spec](https://jcp.org/aboutJava/communityprocess/final/jsr366/index.html), you'll see that this section needs some formatting assistance.  These type of issues may apply to other subsections of this chapter as well (I didn't verify).  If you want to tackle these changes in this PR, that would be fine with me.  Or, if you wish to complete what you have and then do a new PR for these additional updates, that would be fine as well.  Whatever works for you.

Thank you for all of these updates!  Everything else looks great!

**Comment by DmitriGit** [comment]
Hi Kevin,
yes, now I see all problems with this paragraph... 
I'll change formatting in the context of this PR. I'll do it with pleasure and with great attention!
Thank you very much! :)
Dmitri.

**Comment by DmitriGit** [comment]
Confirm me, please, that  the following is a typo:

at the start of the "8.6. Jakarta EE Application XML Schema" section:
"_The root element of the deployment descriptor for a **Jaav** EE application is application ._"
I think it should be:
"_The root element of the deployment descriptor for a **Jakarta** EE application is application ._"

right?

**Comment by kwsutter** [comment]
> Confirm me, please, that the following is a typo:
> 
> at the start of the "8.6. Jakarta EE Application XML Schema" section:
> "_The root element of the deployment descriptor for a **Jaav** EE application is application ._"
> I think it should be:
> "_The root element of the deployment descriptor for a **Jakarta** EE application is application ._"
> 
> right?

Yep.  The c/Java/Jakarta/ doesn't catch typos...  ;-)  Nice catch!

**Comment by DmitriGit** [comment]
One small observation... 
Paragraph "10.5 Application Programmin Interfaces". In the phrase: 
"_as described in Chapter **EE.**6 “Application Programming Interface.”_" i see "EE." as in previous version of Enterprise Edition Specification (Java EE 8). In our version (Jakarta 9) we use links and not the mention "Chapter EE." anymore.

If you confirm that it's a typo I'll adapt it to the current version 9 of "Jakarta Platform Specification".

**Comment by DmitriGit** [comment]
Hello Team, 

I had full immersion in "Jakarta NoSQL", "Jakarta Tutorial" and "Jakarta Connectors" Specifications (for the last one I'm converting now more than 100 not so simple images from JPEG to SVG)...

If you confirm me this: https://github.com/eclipse-ee4j/jakartaee-platform/pull/404#issuecomment-921611692

I'll start to apply changes listed on our posts here, then test on my PC, commit and push.

Thank you very much !!!
Dmitri.

**Review by starksm64 — APPROVED** [review]

**Pull request merged**
