### PR TITLE
create FAQ

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

- Main Jakarta EE 9 page
  - Update with latest information regarding ballots and approvals.  
  - Included a link to the new Release Plan FAQ.
  - Included links to the EJB and Activation Release Plans.
  - Including a link to the github Project Board.

- Jakarta EE 9 Release Plan page
  - Updated the Release Plan with a link to the FAQ.  (As an attempt to keep the Release Plan clean.)

- Jakarta EE 9 Release Plan FAQ
  - Created a new FAQ page for the Jakarta EE 9 Release.  Review this for accuracy.

### CODE REVIEW

**Comment by kwsutter** [comment]
> Very nice! Thanks, Kevin! I'm glad you remember these details better than I do. :-)

Thanks!  I rely on the minutes to jog my memory...  :-)

**Comment by scottmarlow** [comment]
Do we have a list of property names that are in pruned Jakarta EE Projects?  It could be useful to list them for EE 8 -> EE 9 transformation.

**Comment by bshannon** [comment]
> Do we have a list of property names that are in pruned Jakarta EE Projects? It could be useful to list them for EE 8 -> EE 9 transformation.

What do you  mean "property names that are pruned"?  Do you mean the ones whose names
will change?  I think that's a spec-by-spec problem.  Each spec should list this information in
the section that talks about compatibility with the previous release.  If the spec doesn't already
have such a section, it needs one now!  :-)  (Which reminds me, I need to add them to my specs!)

**Comment by kwsutter** [comment]
Thanks for the reviews!  I'm going to go ahead with the merge.  We can adjust as needed.

**Pull request merged**
