### PR TITLE
PNG to SVG images format conversion.

### PR DESCRIPTION
**Pull request by DmitriGit**
Figure 3 and 4 converted and pushed.

### CODE REVIEW

**Review by dmatej — APPROVED** [review]

**Comment by kwsutter** [comment]
Thank you for continuing this image conversion, @DmitriGit!  Much appreciated.  Just to connect the dots, we started this conversion back when we first did Jakarta EE 9 (PR #217).  I have also started to participate in the discussion on the Platform mailing list (https://www.eclipse.org/lists/jakartaee-platform-dev/msg02627.html).  Let's figure out the desired direction from the wider community before we merge these changes in.  Thanks again!

**Comment by DmitriGit** [comment]
Ok, ok! I'll wait for decision and then proceed. Thank you for opportunity to help you. :)

**Comment by kwsutter** [comment]
@DmitriGit I just replied to the Platform mailing list that I feel that svg images are better than png and I don't want to lose out on your contribution.  We can continue debating the pros and cons of the asciidoc images, but as the main maintainer of the Platform doc, I still prefer the svg format.

Can I also ask you to update the Specification Security section to include these svg files instead of png files as part of this PR?  Thanks!

**Comment by DmitriGit** [comment]
Hello, yes I followed the whole debate about possible image format and I'm agree with your decision.

Yes I'll convert soon all images of Platform Specification to SVG format.

Thank you for opportunity! :)

**Comment by kwsutter** [comment]
Thank you, @DmitriGit!

To start with, just updating the references in the spec from png to svg (for the images you have created) would be great!

Did you want to do all of the images via this PR?  Or, should we break them into smaller chunks?  Your call since you are doing the work...  :-)

Thanks again!

**Comment by DmitriGit** [comment]
Yes, I'll update the references in the spec from png to svg - no problem.

Yes, I'll do all of the images via this PR - it's ok for me. :)

Thank you! :)

**Comment by DmitriGit** [comment]
References in the spec from png to svg are updated, commit pushed.  Before push the commit I'he generated the specification on my PC - all is OK - images are visible.

Now I proceed with the rest of images transformation from PNG to SVG.

Thank you,
Dmitri.

**Comment by kwsutter** [comment]
> Now I proceed with the rest of images transformation from PNG to SVG.

How is this exercise coming along, @DmitriGit?  Should we go with what we have for now?  Or, will this coming relatively soon?  It's not an urgent request, just trying to gauge the effort associated with this.  Thanks!

**Comment by DmitriGit** [comment]
Hi Kevin,

all is under control - work in progress ! :) Sorry for silence - I had two weeks of holidays... 

I think I'll push all diagrams within two weeks (so, before 10 August wi will have all diagrams updated).

Thank you.

**Comment by DmitriGit** [comment]
By the way, Kevin, I found some imperfections in the "Platform Specification". And in particular:

1) Tooltip "XML" in some blocks of XML code is absent. For example in the section _"6.2.2.6. Declaring Permissions Required by Application Components"_ - in the block after _"The following is an example of a permission set declaration:"_,

2) Prefix and postfix "..." in some XML blocks are absent, such as:
a. in the section _"5.22. Managed Bean References"_ in the block after _"The following example shows how to declare references to the shopping cart bean..."_
b. in the section _"5.18.8. Connector Administered Object Definition"_ in the block after _"An administered object resource may be defined in a web module, enterprise bean..."_

**and others...**

If you confirm me that there are the things to fix, I'll push that changes along with new format of images.

Let me know.

Thank you,
Dmitri.

**Comment by DmitriGit** [comment]
Hello,

pushed the first converted image ("JavaEEapplication_schema.svg") of the "8.6. Jakarta EE Application XML Schema" paragraph.

Let me know if all is ok and then I'll finish others.

Thank you,
Dmitri.

**Comment by DmitriGit** [comment]
Let me know then if you like my version.
Continue.

**Comment by DmitriGit** [comment]
Done! :)

Let me know if all is ok (I tried to be very careful and I think there are no mistakes, but...).

And let me know, please, about this:
"
_I found some imperfections in the "Platform Specification". And in particular:

Tooltip "XML" in some blocks of XML code is absent. For example in the section "6.2.2.6. Declaring Permissions Required by Application Components" - in the block after "The following is an example of a permission set declaration:",

Prefix and postfix ". . ." in some XML blocks are absent, such as:
a. in the section "5.22. Managed Bean References" in the block after "The following example shows how to declare references to the shopping cart bean..."
b. in the section "5.18.8. Connector Administered Object Definition" in the block after "An administered object resource may be defined in a web module, enterprise bean..."

and others...

If you confirm me that there are the things to fix, I'll push that changes along with new format of images._
"

**Comment by kwsutter** [comment]
@DmitriGit Sorry for the delay!  I was busy with the Jakarta EE 10 Release Plan and then I left on a long(er) vacation.  I am now back!

I will review the updating images.  Thank you!  As far as the other items you found, I would prefer to have them with a separate PR.  Thanks!

**Review by kwsutter — COMMENTED** [review]
@DmitriGit Overall looks very good.  Thank you!

Can you take another look at Figures 22, 23, and 24?  They don't seem quite consistent with the content of the original png files in the Platform spec.

Also, did you get all of the doc references updated to point at the svg files instead of the png files?  

Thanks!
-- Kevin

**Comment by DmitriGit** [comment]
Hello Kevin, I'm very glad you came back and you liked my work! :)

Yes, I'll take a look at Fig 22, 23, 24 and will update doc references! :)

Give me 2 days, please.

Thank you!
Dmitri.

**Comment by DmitriGit** [comment]
> _As far as the other items you found, I would prefer to have them with a separate PR._

Yes, I'll create a new PR but the next week, because I have found some other similar errata and would want to finish reading the Jakarta Platform Specification to be sure to collect all problems in one PR.

Thank you,
Dmitri.

**Comment by kwsutter** [comment]
> Hello Kevin, I'm very glad you came back and you liked my work! :)
> 
> Yes, I'll take a look at Fig 22, 23, 24 and will update doc references! :)
> 
> Give me 2 days, please.
> 
> Thank you!
> Dmitri.

Sounds good!  Thanks, Dmitri.

**Comment by kwsutter** [comment]
> > _As far as the other items you found, I would prefer to have them with a separate PR._
> 
> Yes, I'll create a new PR but the next week, because I have found some other similar errata and would want to finish reading the Jakarta Platform Specification to be sure to collect all problems in one PR.
> 
> Thank you,
> Dmitri.

I'll keep an eye open for these additional updates.  Appreciate the good eyes!

**Comment by DmitriGit** [comment]
> I'll keep an eye open for these additional updates. Appreciate the good eyes!

There are will be the good eyes from me, I promise you! :)
Dmitri.

**Comment by DmitriGit** [comment]
Images 22, 23, 24 updated ! Sorry, but I pushed 3 August horrendous work!
Now it seems ok.

Let me know if, and when, you'll find even if a small imperfection - I'll correct it immediately, but it should be all ok.

Before commit I had generate specification on my PC and verified it - seems ok.
Dmitri.

**Comment by kwsutter** [comment]
> Images 22, 23, 24 updated ! Sorry, but I pushed 3 August horrendous work!
> Now it seems ok.
> 
> Let me know if, and when, you'll find even if a small imperfection - I'll correct it immediately, but it should be all ok.
> 
> Before commit I had generate specification on my PC and verified it - seems ok.
> Dmitri.

Looks great, Dmitri!  Some of my confusion with figures 21 - 24 is that I was looking at the generated spec incorrectly.  But, it all looks good now.  And, the doc references look good as well.  Ready to merge.  Thank you!

**Review by kwsutter — APPROVED** [review]
Great work, @DmitriGit!  Thank you for your efforts on this png -> svg conversion!  I really like the result.

**Pull request merged**
