### PR TITLE
Web Profile Revision History

### PR DESCRIPTION
**Pull request by omoz4real**
Web Profile Revision History

### CODE REVIEW

**Comment by kwsutter** [comment]
@omoz4real Thanks for the PR, but you will need to accept the ECA before we can accept this PR.  Also, it looks like it has some merge conflicts with existing docs.  Just changing too quickly to keep up...  :-). Thanks.

**Comment by omoz4real** [comment]
> @omoz4real Thanks for the PR, but you will need to accept the ECA before we can accept this PR. Also, it looks like it has some merge conflicts with existing docs. Just changing too quickly to keep up... :-). Thanks.

I have tried signing the ECA several times. Maybe I am doing it wrongly.

**Comment by kazumura** [comment]
> I have tried signing the ECA several times. Maybe I am doing it wrongly.

There are two problems.
One is you used anonymous  mail  (omoz4real@****.noreply).
The other is you did not include  "Signed-off-by" footer for  (omoz4real@****.com) .

**Comment by omoz4real** [comment]
> > I have tried signing the ECA several times. Maybe I am doing it wrongly.
> 
> There are two problems.
> One is you used anonymous mail (omoz4real@****.noreply). The other is you did not include "Signed-off-by" footer for (omoz4real@****.com) .

Thanks. I have set my primary email address on Github to my real email address which is used for Github web based operations. I have also used the git config user.name and git config user.email for my local Git account. Is there any more tip of what I could be doing wrong? Thanks a lot.

**Comment by omoz4real** [comment]
> > I have tried signing the ECA several times. Maybe I am doing it wrongly.
> 
> There are two problems.
> One is you used anonymous mail (omoz4real@****.noreply). The other is you did not include "Signed-off-by" footer for (omoz4real@****.com) .

Also, I am trying to do this using the web based Github not from the console. If there is any tip on how to add the "Signed-off-by" footer on my Github account. I have done both from the console on my Git account. Thanks

**Comment by kwsutter** [comment]
Check out the recent conversation on the incubation mailing list.  Another contributor had the same type of signing issues...  It would be good for you to subscribe to this mailing list since that's the first course of action for newbie questions.  Thanks.
https://www.eclipse.org/lists/incubation/msg00668.html

**Comment by kwsutter** [comment]
@omoz4real FYI, Another PR #63 just provided changes for the RelatedDocuments pages.  I just provided review comments on that one.  And, it looks like PR #44 did the Profiles updates already.  But, we still need RevisionHistory if you can clean up this PR.  Thanks!

**Comment by kwsutter** [comment]
It looks like these changes have been incorporated via other PRs, so I'm going to close this one. If you feel there are still changes to be made, please open a new PR. Thank you!

**Pull request closed without merging**
